### ISSUE TITLE
Error:Hit unexpected exception and execution failed

### ISSUE THREAD

**Issue by gaurav7961** [rawatsudhir1/ADFPythonCustomActivity#1]
Hi,
I tried using steps in tutorial, which is using Windows Server 2008 R2 SP1 VM. I installed python 2.7 as well as all required python packages but after running adf, I am getting error as "Activity PythonGetTweets failed: Hit unexpected exception and execution failed." I am not sure what is missing, The errorlogs at batchpool are empty. Can you please help?

**Comment by rawatsudhir1** [comment]
Hi Gaurav7961, 

Sure... Can you run python code on same VM (after rdp) and share outcome here?

**Comment by rawatsudhir1** [comment]
Hey @gaurav7961 I haven't got any reply from you hence assuming you are busy with other business commitment.

I am closing this issue but feel free to let me know here if you need any assistance.
